#!/bin/bash

# Set the base directory for the containers
CONTAINER_DIR=/path/to/containers

# Create the container directory if it doesn't exist
if [ ! -d "$CONTAINER_DIR" ]; then
  mkdir -p "$CONTAINER_DIR"
fi

# Define the menu options
OPTIONS=(
1 "Odoo"
2 "ERPNext"
3 "SuiteCRM"
4 "Invoice Ninja"
5 "Snipe-IT"
6 "Bitwarden"
7 "Mattermost"
8 "Rocket.Chat"
9 "Odoo POS"
10 "Floreant POS"
11 "Taiga"
12 "Redmine"
13 "OrangeHRM"
14 "Sentrifugo"
15 "WooCommerce"
16 "Magento"
17 "GitLab"
18 "Jenkins"
19 "SciPy"
20 "RStudio"
21 "Moodle"
22 "Open edX"
23 "GnuCash"
24 "KMyMoney"
25 "OpenUnderwriter"
26 "SuiteCRM (Insurance Module)"
0 "Download All Containers"
)

# Define the command to download and install a container
INSTALL_CMD="yay -S --noconfirm docker-compose && git clone"

# Loop until the user selects "Quit"
while true; do
  # Show the menu and get the user's selection
  OPTION=$(yad --form --title="Docker Containers" --text="Select a container to download and install:" --button="Download All Containers:0" "${OPTIONS[@]}")

  # Exit if the user clicks "Cancel"
  [ $? -ne 0 ] && exit

  # Check if the user wants to download all containers
  if [ "$OPTION" -eq 0 ]; then
    for i in $(seq 1 $(( ${#OPTIONS[@]} / 2 - 1 ))); do
      CONTAINER=${OPTIONS[$i*2]}
      echo "Downloading and installing $CONTAINER..."
      $INSTALL_CMD "https://github.com/myusername/$CONTAINER.git" "$CONTAINER_DIR/$CONTAINER"
    done
    exit
  fi

  # Get the container name from the user's selection
  CONTAINER=${OPTIONS[$OPTION*2]}

  # Download and install the selected container
  echo "Downloading and installing $CONTAINER..."
  $INSTALL_CMD "https://github.com/myusername/$CONTAINER.git" "$CONTAINER_DIR/$CONTAINER"
done
